config/routes.rb
Rails.application.routes.draw do
  
  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/search', to: 'home#search', as: :search

  # Authentication routes
  resources :sessions
  resources :users
  get 'signup', to: 'users#new', as: :signup
  get 'user/edit', to: 'users#edit', as: :edit_current_user
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

  resources :categories
  resources :items
  resources :subcats
  resources :users
  resources :starred_items
  resources :subcat_items
  
  # You can have the root of your site routed with 'root'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/starred_item.rb
class StarredItem < ApplicationRecord
  # get module to help with some functionality
  include AppHelpers::Validations

  # Relationships
  belongs_to :user
  belongs_to :item

  # Scopes
  scope :for_item,   -> (item_id) { where('item_id = ?', item_id)}
  scope :for_user,   -> (user_id) { where('user_id = ?', user_id)}

  # Validations
  validates :user_id, presence: true, numericality: { greater_than: 0, only_integer: true }
  validates :item_id, presence: true, numericality: { greater_than: 0, only_integer: true }
  validate :item_is_not_already_starred
  validate :user_is_active_in_system
  validate :item_is_active_in_system

  private
  # Custom Validations
  def item_is_not_already_starred
    return true if self.item.nil? || self.user.nil?
    unless StarredItem.where(item_id: self.item_id, user_id: self.user_id).to_a.empty?
      errors.add(:base, "You have already starred this item")
    end
  end

  def user_is_active_in_system
    is_active_in_system(:user)
  end

  def item_is_active_in_system
    is_active_in_system(:item)
  end

end

app/controllers/starred_items_controller.rb
class StarredItemsController < ApplicationController
  
  before_action :check_login
  authorize_resource

  def index
    @starred_items = StarredItem.all
    if (logged_in? && current_user.role?(:customer))
      @my_starred = current_user.starred_items.all
    end
  end

  def new
    @star = StarredItem.new
  end

  def create
    @star = StarredItem.new(starred_item_params)
    if @star.save
      redirect_to user_path(@star.user)
    else
      render action: 'new'
    end
  end

  # def destroy
  # end

  private

  def starred_item_params
    params.require(:starred_item).permit(:user_id, :item_id)
  end
  
end

app/helpers/starred_items_helper.rb
module StarredItemsHelper
end

app/views/starred_items/_starred_items.html.erb
<h4 >Starred Items</h4>

<table class="striped highlight">
  <thead>
    <th>Title</th>
    <th>link</th>
    <th>featured</th>
  </thead>
  <% for si in @starred_items %>
    <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
      <td><%= link_to si.item.title, item_path(item) %></td>
      <td><%= si.item.link %></td>
      <td><%= si.item.featured %></td>
    <td class="align_center">
      <%= link_to edit_starred_item_path(si) do %>
            <i class="material-icons">edit</i>
      <% end %>
      &nbsp;&nbsp;&nbsp;&nbsp; 
      <%= link_to(starred_item_path(si), method: :delete, data: { confirm: 'Are you sure you wish to delete this information?' }) do %>
          <i class="material-icons">delete</i>
      <% end %>
    </td>
    </tr>
  <% end %>
</table>

app/views/starred_items/index.html.erb
<%= render partial: "partials/structure1", locals: {model_name: "starred_item", 
                                                         primary: "starred_items", 
                                                         secondary: nil,
                                                         sidebar: nil} %>

<p>&nbsp;</p>
<%# <%= render :partial => "partials/add_new_object", locals: {model_name: 'starred_item'} %>

app/views/starred_items/new.html.erb
<h1>StarredItems#new</h1>
<p>Find me in app/views/starred_items/new.html.erb</p>

app/views/starred_items/show.html.erb
<h1>StarredItems#show</h1>
<p>Find me in app/views/starred_items/show.html.erb</p>