config/routes.rb
Rails.application.routes.draw do
  
  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/search', to: 'home#search', as: :search

  # Authentication routes
  resources :sessions
  resources :users
  get 'signup', to: 'users#new', as: :signup
  get 'user/edit', to: 'users#edit', as: :edit_current_user
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

  resources :categories
  resources :items
  resources :subcats
  resources :users
  resources :starred_items
  resources :subcat_items
  
  # You can have the root of your site routed with 'root'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/nav/_nav.html.erb
<%= render "partials/nav/nav_dropdown" %>

<nav id="nav">
  <div class="nav-wrapper">
    <div class="container">
      <a href="/home"><%= image_tag 'temp-logo.png'%></a>
      <ul class="right hide-on-med-and-down">
      <% if logged_in? && current_user.role?(:manager)%>
        <li><%= link_to 'Items', items_path %></li>
        <li><%= link_to 'Categories', categories_path %></li>
        <li><%= link_to 'Subcats', subcats_path %></li>
        <li><%= link_to 'Users', users_path %></li>
        <li><a class = "dropdown-trigger" href="/users" data-target="account">Account<i class="material-icons right">arrow_drop_down</i></a></li>
      <% elsif logged_in? && current_user.role?(:admin)%>
        <li><%= link_to 'Items', items_path %></li>
        <li><%= link_to 'Categories', categories_path %></li>
        <li><%= link_to 'Subcats', subcats_path %></li>
        <li><%= link_to 'Users', users_path %></li>
        <li><a class = "dropdown-trigger" href="/users" data-target="account">Account<i class="material-icons right">arrow_drop_down</i></a></li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/partials/nav/_nav_customer.html.erb
<%= render "partials/nav/nav_dropdown" %>


<ul id="slide-out" class="sidenav sidenav-fixed">
  <a href="/home"><%= image_tag 'temp-logo.png'%></a>
  <li class="no-padding">
  <li><a class = "dropdown-trigger" href="/users" data-target="account">Account<i class="material-icons right">arrow_drop_down</i></a></li>
    <ul class="collapsible collapsible-accordion">
      <% for cat in nav_cats.active %>
        <li>
          <a class="collapsible-header"><%= cat.name %><i class="material-icons right">arrow_drop_down</i></a>
          <div class="collapsible-body">
            <ul>
              <% for sc in nav_subcats.for_category(cat).all %>
                <li><%= link_to sc.name, subcat_path(sc) %></li>
              <% end %>
            </ul>
          </div>
        </li>
      <% end %>
    </ul>
  </li>
</ul>
<a href="#" data-target="slide-out" class="sidenav-trigger show-on-large"><i class="material-icons">menu</i></a>

app/views/partials/nav/_nav_dropdown.html.erb
<ul id="item" class="dropdown-content">
  <li><%= link_to "Item List", items_path%></li>
  <li><%= link_to "New Item", new_item_path %></li>
</ul>

<ul id="user" class="dropdown-content">
  <li><%= link_to "User List", users_path %></li>
  <li><%= link_to "New User", new_user_path %></li>
</ul>


<ul id="account" class="dropdown-content">
  <% if logged_in? %>
    <!-- manager -->
    <% if current_user.role?(:manager) %>
      <li><%= link_to "My Account", user_path(current_user) %></li>
      <li><%= link_to "Logout", logout_path %></li>
  	
    <!-- customer -->
    <% elsif current_user.role?(:customer) %>
  		<li><%= link_to "My Account", user_path(current_user) %></li>
      <li><%= link_to "Starred Items", starred_items_path%>
  	  <li><%= link_to "Logout", logout_path %></li>

    <!-- admin -->
    <% else %>
      <li><%= link_to "My Account", user_path(current_user) %></li>
  	  <li><%= link_to "Logout", logout_path %></li>
    <% end %>
	<% end %>
</ul>

<% for cat in nav_cats.active %>
  <ul id=<%= cat.name%> class="dropdown-content">
  <% for sc in nav_subcats.for_category(cat).all %>
    <li><%= link_to sc.name, subcat_path(sc) %></li>
  <% end %>
  </ul>
<%end%>
  

app/views/partials/nav/_nav_guest.html.erb
<%= render "partials/nav/nav_dropdown" %>

<nav id="nav">
  <div class="nav-wrapper">
    <div class="container">
      <a href="/home"><%= image_tag 'temp-logo.png'%></a>
      <ul class="right hide-on-med-and-down">
      <% for cat in nav_cats.active %>
        <li><a class = "dropdown-trigger" href="/categories" data-target=<%=cat.name%>><%= cat.name %><i class="material-icons right">arrow_drop_down</i></a></li>
      <% end %>
      <li><a href="/login"><i class="material-icons right">exit_to_app</i>Login</a></li>
      <li><a href="/signup"><i class="material-icons right">assignment</i>Sign Up</a></li>
      </ul>
    </div>
  </div>
</nav>