config/routes.rb
Rails.application.routes.draw do
  
  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/search', to: 'home#search', as: :search

  # Authentication routes
  resources :sessions
  resources :users
  get 'signup', to: 'users#new', as: :signup
  get 'user/edit', to: 'users#edit', as: :edit_current_user
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

  resources :categories
  resources :items
  resources :subcats
  resources :users
  resources :starred_items
  resources :subcat_items
  
  # You can have the root of your site routed with 'root'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  include AppHelpers::Activeable::InstanceMethods
  extend AppHelpers::Activeable::ClassMethods
  
  # Relationships
  has_many :subcats

  # Scopes
  scope :alphabetical, -> { order(:name) }

  # Validations
  validates :name, presence: true, uniqueness: { case_sensitive: false }

  # Callbacks
  before_destroy do 
    check_if_subcats_empty
    if errors.present?
      @destroyable = false
      throw(:abort)
    end
  end
  
  after_rollback :make_inactive_if_trying_to_destroy
 
  # Other methods
  attr_reader :destroyable
  
  private
  def check_if_subcats_empty
    unless no_subcats?
      errors.add(:base, "Category cannot be deleted because it contains sub-categories, but its status has been set to inactive.")
    end
  end

  def no_subcats?
    self.subcats.empty?
  end

  def make_inactive_if_trying_to_destroy
    if !@destroyable.nil? && @destroyable == false
      self.subcats.each{ |subcat| subcat.make_inactive }
      self.make_inactive
    end
    @destroyable = nil
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  before_action :set_category, only: [:show, :edit, :update]
  before_action :check_login, only: [:edit, :update, :destroy, :new, :create]
  authorize_resource

  def index
    @active_cats = Category.active.all
    @inactive_cats = Category.inactive.all
  end

  def new
    @cat = Category.new
  end

  def create
    @cat = Category.new(category_params)
    if @cat.save
      redirect_to categories_path, notice: "Category #{@cat.name} was added to the system."
    else
      render action: 'new'
    end
  end

  def show
    @cat_subcats = @cat.subcats.all
  end

  def edit
  end

  def update
    if @cat.update(category_params)
      redirect_to categories_path, notice: "Category #{@cat.name} was updated."
    else
      render action: 'edit'
    end
  end

  # def destroy
  # end

  private

  def set_category
    @cat = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :active)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_active_categories.html.erb
<h4 >Active Categories</h4>

<table class="striped highlight">
  <thead>
    <th>Name</th>
    <th># of Sub Categories</th>
  </thead>
  <% for cat in @active_cats %>
    <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
      <td><%= link_to cat.name, category_path(cat) %></td>
      <td><%= cat.subcats.count %></td>
    <td class="align_center">
      <%= link_to edit_category_path(cat) do %>
            <i class="material-icons">edit</i>
      <% end %>
      &nbsp;&nbsp;&nbsp;&nbsp; 
      <%= link_to(category_path(cat), method: :delete, data: { confirm: 'Are you sure you wish to delete this information?' }) do %>
          <i class="material-icons">delete</i>
      <% end %>
    </td>
    </tr>
  <% end %>
</table>

app/views/categories/_category_details.html.erb
<h4 ><%= @cat.name %> Sub Categories</h4>

<table class="striped highlight">
  <thead>
    <th>Name</th>
    <th>Number of Items</th>
  </thead>
  <% for subcat in @cat_subcats %>
    <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
      <td><%= link_to subcat.name, subcat_path(subcat) %></td>
      <td><%= subcat.subcat_items.count %></td>
    <td class="align_center">
      <%= link_to edit_subcat_path(subcat) do %>
            <i class="material-icons">edit</i>
      <% end %>
      &nbsp;&nbsp;&nbsp;&nbsp; 
      <%= link_to(subcat_path(subcat), method: :delete, data: { confirm: 'Are you sure you wish to delete this information?' }) do %>
          <i class="material-icons">delete</i>
      <% end %>
    </td>
    </tr>
  <% end %>
</table>

app/views/categories/_fields.html.erb
<%= f.input :name, label_html: { class: 'active' } %>
<br><br><br><br>
<%= f.input :active %>

app/views/categories/_inactive_categories.html.erb
<% unless @inactive_cats.empty? %>
  <div class="card lighten-4">
    <div class="card-content">
      <span class="card-title">Inactive Categories</span>
      <ul>
        <% for cat in @inactive_cats %>
          <li><%= link_to cat.name, category_path(cat) %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%= render partial: "partials/form_structure", locals: {object: @cat, 
                                                        type_of_form: "Edit Category",
                                                        fields: "fields"} %>

app/views/categories/index.html.erb
<%= render partial: "partials/structure1", locals: {model_name: "category", 
                                                         primary: "active_categories", 
                                                         secondary: nil,
                                                         sidebar: "inactive_categories"} %>
                                                         
<%= render :partial => "partials/add_new_object", locals: {model_name: 'category'} %>

app/views/categories/new.html.erb
<%= render partial: "partials/form_structure", locals: {object: @cat, 
                                                        type_of_form: "New Category",
                                                        fields: "fields"} %>

app/views/categories/show.html.erb
<%= render partial: "partials/structure2", locals: {model_name: "category", 
                                                         object: @cat,
                                                         primary: "category_details", 
                                                         secondary: nil,
                                                         sidebar: nil} %>